### ISSUE TITLE
[1월 1일~ 1월 1일] 안드로이드 TODO

### ISSUE THREAD

**Issue by vkeh2431** [Gachon-P-project/Front#12]
## 주요 내용
- [x] dependency injection 라이브러리인 dagger 2 이해하기.
- [x] mvvm pattern 이해하기.
- [ ] 위 2개가 이용된 오픈소스 분석하기.

## 상세 내용
1. dagger 2
    - annotaion
    - logic  

2. mvvm
    - model
    - view
    - viewmodel
